Adds Advantages
makaronnik/ice-cream-landing pull request #1
Opened 2022-12-23 14:31 UTC by Nataly-Moskalenko

2022-12-23 20:19 UTC, makaronnik requested changes
Потрібно видалити зайвий код у коментарях і обов'язково, перед новим пушем, синхронізуватися з актуальною гілкою main

2022-12-23 20:19 UTC, makaronnik commented on src/index.html
>  <html lang="en">
Ти перед пулл-реквестом не сихронізувала гілку main зі своєю гілкою, тому виник конфлікт у коді. Запусти у себе зі своєї гілки у консолі, по черзі, команди: 
git pul orirgin main
git merge main

2022-12-23 20:19 UTC, makaronnik commented on src/sass/components/_advantages.scss
> +    /* padding-top: 50px; */
Код що не знадобився (код у коментарях) потрібно видаляти

2022-12-23 20:19 UTC, makaronnik commented on src/sass/components/_advantages.scss
> +        /* padding-top: 60px; */
Код що не знадобився (код у коментарях) потрібно видаляти

2022-12-24 08:39 UTC, Nataly-Moskalenko commented
Зайвий код (у коментах) видалила. Синхронізувалась з main.

2022-12-24 10:59 UTC, makaronnik approved these changes

2022-12-24 11:00 UTC, merged