added contacts section html and scc
makaronnik/ice-cream-landing pull request #4
Opened 2022-12-24 12:11 UTC by DianaShe

2022-12-24 14:59 UTC, makaronnik requested changes
Поки тільки код подивився. Виправ, будь ласка.

2022-12-24 14:59 UTC, makaronnik commented on src/partials/_contacts.html
> +<body>
Навіщо це тут?

2022-12-24 14:59 UTC, makaronnik commented on src/partials/_contacts.html
> +</html>
І це?

2022-12-24 14:59 UTC, makaronnik commented on src/sass/components/_agency.scss
> +
Зайвий відступ

2022-12-24 14:59 UTC, makaronnik commented on src/sass/components/_agency.scss
> +
Зайвий відступ

2022-12-24 14:59 UTC, makaronnik commented on src/sass/components/_agency.scss
> +
Зайвий відступ

2022-12-24 14:59 UTC, makaronnik commented on src/sass/components/_agency.scss
> +
Зайвий відступ

2022-12-24 14:59 UTC, makaronnik commented on src/sass/components/_agency.scss
> +
Зайвий відступ

2022-12-24 14:59 UTC, makaronnik commented on src/sass/components/_contacts.scss
> +
Зайвий відступ

2022-12-24 14:59 UTC, makaronnik commented on src/sass/components/_contacts.scss
> +
Зайвий відступ

2022-12-24 18:17 UTC, DianaShe commented on src/sass/components/_agency.scss
> +
перезаписує падінги таблета. в десктопа всі по 40

2022-12-24 18:19 UTC, DianaShe commented on src/sass/components/_agency.scss
> +
тут або подвійне правило для таблета (мін і макс) або так, бо від 768 і вище падінг буде 12, а на десктопі треба 8

2022-12-24 18:19 UTC, DianaShe commented on src/sass/components/_agency.scss
> +
він не зайвий, було 48, з таблета 64

2022-12-24 18:21 UTC, DianaShe commented on src/sass/components/_contacts.scss
> +
чому зайвий? відступ до футера. від верхнього елемента до нижнього

2022-12-24 18:22 UTC, DianaShe commented on src/sass/components/_contacts.scss
> +
не зрозуміла зауваження

2022-12-25 08:06 UTC, makaronnik commented on src/sass/components/_contacts.scss
> +
Я мав на увазі відступ у коді (зайві пусті строки). Вибач, не зрозуміло написав

2022-12-25 08:06 UTC, makaronnik commented on src/sass/components/_contacts.scss
> +
Я мав на увазі відступ у коді (зайві пусті строки). Вибач, не зрозуміло написав

2022-12-25 08:06 UTC, makaronnik commented on src/sass/components/_agency.scss
> +
Я мав на увазі відступ у коді (зайві пусті строки). Вибач, не зрозуміло написав

2022-12-25 08:06 UTC, makaronnik commented on src/sass/components/_agency.scss
> +
Я мав на увазі відступ у коді (зайві пусті строки). Вибач, не зрозуміло написав

2022-12-25 08:06 UTC, makaronnik commented on src/sass/components/_agency.scss
> +
Я мав на увазі відступ у коді (зайві пусті строки). Вибач, не зрозуміло написав

2022-12-25 08:06 UTC, makaronnik commented on src/sass/components/_agency.scss
> +
Я мав на увазі відступ у коді (зайві пусті строки). Вибач, не зрозуміло написав

2022-12-25 08:06 UTC, makaronnik commented on src/sass/components/_agency.scss
> +
Я мав на увазі відступ у коді (зайві пусті строки). Вибач, не зрозуміло написав

2022-12-26 14:08 UTC, makaronnik approved these changes

2022-12-26 14:14 UTC, makaronnik commented
Merged manually

2022-12-26 14:14 UTC, merged